# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b10983d515c8a9d05258396916e45669cf4a44fa3d882f186cc29b70cce7157d359393c8f38a0dc289ebbe4c5e4c14fcfd511307fb37b47750d16b8d7df0b30

test:
  secret_key_base: c4984a030b966d3227efe394758619d92eb8d8a865afca5a36d5ff38a80daf9a4713b94ed864c8f2f4d7f27d7fc670f878ca2b5e3bcc8bff6f7fd2eb3ae62e84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
